--- # Error handling example #2
- hosts: localhost
  become: yes
  vars:
    target_service: openvpn-client
  tasks:
    - name: Install Software
      block:
        - service:
            name: "{{ target_service }}"
            state: started
          register: service_status
      rescue:
        - debug: 
            var: service_status
      always:
        - debug: 
            msg: "Tried to ensure service was running"
